### ISSUE TITLE
xml -> compose 전환 검토

### ISSUE THREAD

**Issue by YoonJaePark3908** [YoonJaePark3908/StockPortfolio#16]
databinding이 적용 돼 있기 때문에 문제 없어 보이긴 하나, 좌우 스와이프 레이아웃 기술에 대한 연구가 더 필요할 것으로 보임

**Comment by YunJaePark3908** [comment]
databinding이 적용 돼 있기 때문에 문제 없어 보이긴 하나, 좌우 스와이프 레이아웃 기술에 대한 연구가 더 필요할 것으로 보임
